name: Run add-apps.ps1 on Push

on: 
  push:
    branches:
      - main
    paths:
      - 'config.json'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        Install-Module -Name wintuner -Force -Scope CurrentUser

    - name: Run add-apps.ps1
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: ./add-apps.ps1
      shell: pwsh