name: Run update-apps.ps1 on Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        Install-Module -Name wintuner -Force -Scope CurrentUser

    - name: Run update-apps.ps1
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: ./update-apps.ps1
      shell: pwsh