name: Run update-apps.ps1 on Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        Install-Module -Name wintuner -Force -Scope CurrentUser

    - name: Run update-apps.ps1
      run: ./update-apps.ps1
      shell: pwsh